export { default as ProfilePage } from "./ProfilePage";
export { default as AuthPage } from "./AuthPage";
export { default as NotFoundPage } from "./NotFoundPage";
export { default as AboutPage } from "./AboutPage";
export { default as RegisterPage } from "./RegisterPage";
export { default as HomePage } from "./HomePage";
export { default as AdminPage } from "./AdminPage";
export { default as CartPage } from "./CartPage";
export { default as CategoryPage } from "./CategoryPage";
export { default as CollectionPage } from "./CollectionPage";
export { default as PrivacyPage } from "./PrivacyPage";
export { default as ProductPage } from "./ProductPage";
export { default as ContactPage } from "./ContactPage";
export { default as ChangePassword } from "./ChangePassword";
export { default as OrdersPage } from "./OrdersPage"